# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from functools import partial

from PyQt5 import QtCore, QtGui, QtWidgets

from src.visual.PrologRepositorio import PrologRepositorio


class AireLugar(object):
    def __init__(self, lugar):
        self.lugar = lugar
        self.prolog = PrologRepositorio()

    def actualizar_gui(self):
        info = self.prolog.get_info_aire(self.lugar)
        self.lbl_temp.setText(str(info[1]))
        self.lbl_unidad.setText("Celsius")
        self.lbl_estado.setText(info[0])

    def init_view(self):
        info = self.prolog.get_info_aire(self.lugar)
        self.cambiar_estado_btns_vel(True)
        self.cambiar_estado_btns_modo(True)
        self.actualizar_gui()
        if info[0] == "apagado":
            self.btn_subir_temp.setDisabled(True)
            self.btn_bajar_temp.setDisabled(True)
        else:
            self.get_modo_actual()
            self.get_vel_actual()
            self.btn_subir_temp.setDisabled(False)
            self.btn_bajar_temp.setDisabled(False)

    def get_modo_actual(self):
        info = self.prolog.get_info_aire(self.lugar)
        self.cambiar_estado_btns_modo(False)
        if info[2] == "frio":
            self.btn_modo_frio.setDisabled(True)
        elif info[2] == "auto":
            self.btn_modo_auto.setDisabled(True)
        else:
            self.btn_modo_seco.setDisabled(True)

    def get_vel_actual(self):
        info = self.prolog.get_info_aire(self.lugar)
        self.cambiar_estado_btns_vel(False)
        if info[3] == "alto":
            self.btn_vel_alto.setDisabled(True)
        elif info[3] == "medio":
            self.btn_vel_media.setDisabled(True)
        else:
            self.btn_vel_baja.setDisabled(True)

    def encender_apagar(self):
        info = self.prolog.get_info_aire(self.lugar)
        if info[0] == "apagado":
            self.prolog.actualizar_info_aire(self.lugar, "encendido", info[1], info[2], info[3])
            self.btn_subir_temp.setDisabled(False)
            self.btn_bajar_temp.setDisabled(False)
            self.get_modo_actual()
            self.get_vel_actual()
        else:
            self.prolog.actualizar_info_aire(self.lugar, "apagado", info[1], info[2], info[3])
            self.btn_subir_temp.setDisabled(True)
            self.btn_bajar_temp.setDisabled(True)
            self.cambiar_estado_btns_vel(True)
            self.cambiar_estado_btns_modo(True)
        self.actualizar_gui()

    def cambiar_estado_btns_vel(self, estado):
        self.btn_vel_alto.setDisabled(estado)
        self.btn_vel_media.setDisabled(estado)
        self.btn_vel_baja.setDisabled(estado)

    def cambiar_estado_btns_modo(self, estado):
        self.btn_modo_auto.setDisabled(estado)
        self.btn_modo_frio.setDisabled(estado)
        self.btn_modo_seco.setDisabled(estado)

    def cambiar_modo_auto(self):
        info = self.prolog.get_info_aire(self.lugar)
        self.prolog.actualizar_info_aire(self.lugar, info[0], info[1], "auto", info[3])
        self.actualizar_gui()
        self.cambiar_estado_btns_modo(False)
        self.btn_modo_auto.setDisabled(True)

    def cambiar_modo_frio(self):
        info = self.prolog.get_info_aire(self.lugar)
        self.prolog.actualizar_info_aire(self.lugar, info[0], info[1], "frio", info[3])
        self.cambiar_estado_btns_modo(False)
        self.actualizar_gui()
        self.btn_modo_frio.setDisabled(True)

    def cambiar_modo_seco(self):
        info = self.prolog.get_info_aire(self.lugar)
        self.prolog.actualizar_info_aire(self.lugar, info[0], info[1], "seco", info[3])
        self.cambiar_estado_btns_modo(False)
        self.actualizar_gui()
        self.btn_modo_seco.setDisabled(True)

    def cambiar_vel_alta(self):
        info = self.prolog.get_info_aire(self.lugar)
        self.prolog.actualizar_info_aire(self.lugar, info[0], info[1], info[2], "alto")
        self.cambiar_estado_btns_vel(False)
        self.actualizar_gui()
        self.btn_vel_alto.setDisabled(True)

    def cambiar_vel_media(self):
        info = self.prolog.get_info_aire(self.lugar)
        self.prolog.actualizar_info_aire(self.lugar, info[0], info[1], info[2], "medio")
        self.cambiar_estado_btns_vel(False)
        self.actualizar_gui()
        self.btn_vel_media.setDisabled(True)

    def cambiar_vel_baja(self):
        info = self.prolog.get_info_aire(self.lugar)
        self.prolog.actualizar_info_aire(self.lugar, info[0], info[1], info[2], "bajo")
        self.cambiar_estado_btns_vel(False)
        self.actualizar_gui()
        self.btn_vel_baja.setDisabled(True)

    def subir_temp(self):
        info = self.prolog.get_info_aire(self.lugar)
        self.prolog.actualizar_info_aire(self.lugar, info[0], info[1] + 1, info[2], info[3])
        self.actualizar_gui()

    def bajar_temp(self):
        info = self.prolog.get_info_aire(self.lugar)
        self.prolog.actualizar_info_aire(self.lugar, info[0], info[1] - 1, info[2], info[3])
        self.actualizar_gui()

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(482, 291)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(90, 20, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lbl_temp = QtWidgets.QLabel(Dialog)
        self.lbl_temp.setGeometry(QtCore.QRect(260, 20, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_temp.setFont(font)
        self.lbl_temp.setObjectName("lbl_temp")
        self.lbl_unidad = QtWidgets.QLabel(Dialog)
        self.lbl_unidad.setGeometry(QtCore.QRect(320, 20, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_unidad.setFont(font)
        self.lbl_unidad.setObjectName("lbl_unidad")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lbl_estado = QtWidgets.QLabel(Dialog)
        self.lbl_estado.setGeometry(QtCore.QRect(100, 70, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_estado.setFont(font)
        self.lbl_estado.setObjectName("lbl_estado")
        self.btn_bajar_temp = QtWidgets.QPushButton(Dialog)
        self.btn_bajar_temp.setGeometry(QtCore.QRect(90, 110, 71, 51))
        self.btn_bajar_temp.setObjectName("btn_bajar_temp")
        self.btn_subir_temp = QtWidgets.QPushButton(Dialog)
        self.btn_subir_temp.setGeometry(QtCore.QRect(290, 110, 71, 51))
        self.btn_subir_temp.setObjectName("btn_subir_temp")
        self.btn_encender = QtWidgets.QPushButton(Dialog)
        self.btn_encender.setGeometry(QtCore.QRect(170, 110, 111, 51))
        self.btn_encender.setObjectName("btn_encender")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(20, 200, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(20, 250, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.btn_modo_auto = QtWidgets.QPushButton(Dialog)
        self.btn_modo_auto.setGeometry(QtCore.QRect(190, 200, 75, 23))
        self.btn_modo_auto.setObjectName("btn_modo_auto")
        self.btn_modo_frio = QtWidgets.QPushButton(Dialog)
        self.btn_modo_frio.setGeometry(QtCore.QRect(280, 200, 75, 23))
        self.btn_modo_frio.setObjectName("btn_modo_frio")
        self.btn_modo_seco = QtWidgets.QPushButton(Dialog)
        self.btn_modo_seco.setGeometry(QtCore.QRect(370, 200, 75, 23))
        self.btn_modo_seco.setObjectName("btn_modo_seco")
        self.btn_vel_alto = QtWidgets.QPushButton(Dialog)
        self.btn_vel_alto.setGeometry(QtCore.QRect(190, 250, 75, 23))
        self.btn_vel_alto.setObjectName("btn_vel_alto")
        self.btn_vel_media = QtWidgets.QPushButton(Dialog)
        self.btn_vel_media.setGeometry(QtCore.QRect(280, 250, 75, 23))
        self.btn_vel_media.setObjectName("btn_vel_media")
        self.btn_vel_baja = QtWidgets.QPushButton(Dialog)
        self.btn_vel_baja.setGeometry(QtCore.QRect(370, 250, 75, 23))
        self.btn_vel_baja.setObjectName("btn_vel_baja")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.btn_encender.clicked.connect(partial(self.encender_apagar))
        self.btn_modo_auto.clicked.connect(partial(self.cambiar_modo_auto))
        self.btn_modo_frio.clicked.connect(partial(self.cambiar_modo_frio))
        self.btn_modo_seco.clicked.connect(partial(self.cambiar_modo_seco))
        self.btn_vel_alto.clicked.connect(partial(self.cambiar_vel_alta))
        self.btn_vel_media.clicked.connect(partial(self.cambiar_vel_media))
        self.btn_vel_baja.clicked.connect(partial(self.cambiar_vel_baja))
        self.btn_subir_temp.clicked.connect(partial(self.subir_temp))
        self.btn_bajar_temp.clicked.connect(partial(self.bajar_temp))

        self.init_view()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Temperatura Actual:"))
        self.lbl_temp.setText(_translate("Dialog", "Temp"))
        self.lbl_unidad.setText(_translate("Dialog", "unidad"))
        self.label_4.setText(_translate("Dialog", "Estado:"))
        self.lbl_estado.setText(_translate("Dialog", "Estado"))
        self.btn_bajar_temp.setText(_translate("Dialog", "▼"))
        self.btn_subir_temp.setText(_translate("Dialog", "▲"))
        self.btn_encender.setText(_translate("Dialog", "Apagar/Encender"))
        self.label_10.setText(_translate("Dialog", "Modo:"))
        self.label_11.setText(_translate("Dialog", "Velocidad Abanico:"))
        self.btn_modo_auto.setText(_translate("Dialog", "Auto"))
        self.btn_modo_frio.setText(_translate("Dialog", "Frio"))
        self.btn_modo_seco.setText(_translate("Dialog", "Seco"))
        self.btn_vel_alto.setText(_translate("Dialog", "Alto"))
        self.btn_vel_media.setText(_translate("Dialog", "Medio"))
        self.btn_vel_baja.setText(_translate("Dialog", "Bajo"))

# if __name__ == "__main__":
#     import sys
#
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_Dialog("asd")
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
