# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'miembros_familiares2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from src.visual.PrologRepositorio import PrologRepositorio


class FamiliaMonitor(object):

    def __init__(self):
        self.prolog = PrologRepositorio()
        self.listado_miembros = None
        self.lugares = None

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(525, 309)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(160, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.miembros = QtWidgets.QListWidget(Dialog)
        self.miembros.setGeometry(QtCore.QRect(30, 90, 161, 192))
        self.miembros.setObjectName("miembros")
        self.cbx_estados = QtWidgets.QComboBox(Dialog)
        self.cbx_estados.setGeometry(QtCore.QRect(320, 90, 171, 22))
        self.cbx_estados.setObjectName("cbx_estados")
        self.cbx_estados.addItem("")
        self.cbx_estados.addItem("")
        self.cbx_lugares = QtWidgets.QComboBox(Dialog)
        self.cbx_lugares.setGeometry(QtCore.QRect(320, 130, 171, 22))
        self.cbx_lugares.setObjectName("cbx_lugares")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(210, 90, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(210, 130, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btn_actualizar = QtWidgets.QPushButton(Dialog)
        self.btn_actualizar.setGeometry(QtCore.QRect(220, 200, 111, 81))
        self.btn_actualizar.setObjectName("btn_actualizar")
        self.simular_intruso = QtWidgets.QPushButton(Dialog)
        self.simular_intruso.setGeometry(QtCore.QRect(360, 200, 111, 81))
        self.simular_intruso.setObjectName("simular_intruso")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.lugares = self.prolog.obtener_lugares()
        self.listado_miembros = self.prolog.obtener_miembros_casa()
        self.init_view()
        self.miembros.itemClicked.connect(self.seleccionar_miembro)
        self.simular_intruso.clicked.connect(self.prolog.simular_intruso)
        self.btn_actualizar.clicked.connect(self.actualizar_datos)

    def init_view(self):
        self.miembros.addItems(self.listado_miembros)
        self.cbx_lugares.addItems(self.lugares)
        self.cbx_lugares.setDisabled(True)
        self.cbx_estados.setDisabled(True)

    def seleccionar_miembro(self):
        self.cbx_lugares.setDisabled(False)
        self.cbx_estados.setDisabled(False)
        nombre = self.miembros.selectedItems()[0].text()
        print(nombre)
        estado = self.prolog.obtener_estado_persona(nombre)
        lugar = self.prolog.obtener_lugar_persona(nombre)
        self.cbx_estados.setCurrentIndex(self.cbx_estados.findText(estado))
        self.cbx_lugares.setCurrentIndex(self.cbx_lugares.findText(lugar))

    def actualizar_datos(self):
        nombre = self.miembros.selectedItems()[0].text()
        estado = self.cbx_estados.currentText()
        lugar = self.cbx_lugares.currentText()
        self.prolog.actualizar_persona_totalidad(nombre, lugar, estado)
        estado = self.prolog.obtener_estado_persona(nombre)
        lugar = self.prolog.obtener_lugar_persona(nombre)
        self.cbx_estados.setCurrentIndex(self.cbx_estados.findText(estado))
        self.cbx_lugares.setCurrentIndex(self.cbx_lugares.findText(lugar))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Miembros Familia"))
        self.label.setText(_translate("Dialog", "Miembros Familiares"))
        self.cbx_estados.setItemText(0, _translate("Dialog", "despierto"))
        self.cbx_estados.setItemText(1, _translate("Dialog", "durmiendo"))
        self.label_2.setText(_translate("Dialog", "Estado actual:"))
        self.label_3.setText(_translate("Dialog", "Lugar Actual:"))
        self.btn_actualizar.setText(_translate("Dialog", "Actualizar Estado"))
        self.simular_intruso.setText(_translate("Dialog", "Simular Intruso"))