# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detalleobjeto.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from functools import partial

from PyQt5 import QtCore, QtWidgets

from src.visual.Helper import determinar_icono_objeto
from src.visual.PrologRepositorio import PrologRepositorio
from src.visual.QtHelper import set_img_to_label


class ShVistaObjeto(object):

    def __init__(self, objeto):
        self.objeto = objeto
        self.prologRepository = PrologRepositorio()

    def setupUi(self, dialogo_objeto):
        dialogo_objeto.setObjectName("dialogo_objeto")
        dialogo_objeto.resize(501, 285)
        self.label = QtWidgets.QLabel(dialogo_objeto)
        self.label.setGeometry(QtCore.QRect(20, 20, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(dialogo_objeto)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 71, 16))
        self.label_2.setObjectName("label_2")
        self.btn_encender = QtWidgets.QPushButton(dialogo_objeto)
        self.btn_encender.setGeometry(QtCore.QRect(130, 220, 101, 41))
        self.btn_encender.setObjectName("btn_encender")
        self.btn_apagar = QtWidgets.QPushButton(dialogo_objeto)
        self.btn_apagar.setGeometry(QtCore.QRect(20, 220, 101, 41))
        self.btn_apagar.setObjectName("btn_apagar")
        self.img_objeto = QtWidgets.QLabel(dialogo_objeto)
        self.img_objeto.setGeometry(QtCore.QRect(310, 40, 161, 131))
        self.img_objeto.setText("")
        self.img_objeto.setObjectName("img_objeto")
        self.label_6 = QtWidgets.QLabel(dialogo_objeto)
        self.label_6.setGeometry(QtCore.QRect(20, 80, 71, 16))
        self.label_6.setObjectName("label_6")
        self.lbl_nombre = QtWidgets.QLabel(dialogo_objeto)
        self.lbl_nombre.setGeometry(QtCore.QRect(130, 20, 81, 16))
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.lbl_tipo = QtWidgets.QLabel(dialogo_objeto)
        self.lbl_tipo.setGeometry(QtCore.QRect(130, 50, 61, 16))
        self.lbl_tipo.setObjectName("lbl_tipo")
        self.lbl_estado = QtWidgets.QLabel(dialogo_objeto)
        self.lbl_estado.setGeometry(QtCore.QRect(130, 80, 61, 16))
        self.lbl_estado.setObjectName("lbl_estado")

        self.retranslateUi(dialogo_objeto)
        QtCore.QMetaObject.connectSlotsByName(dialogo_objeto)
        self.iniciar()
        self.llenar_datos()
        self.btn_encender.clicked.connect(partial(self.encender))
        self.btn_apagar.clicked.connect(partial(self.apagar))

    def encender(self):
        self.btn_apagar.setDisabled(False)
        self.btn_encender.setDisabled(True)
        self.prologRepository.abrir_objeto(self.objeto)
        self.lbl_estado.setText(self.prologRepository.obtener_estado_objeto(self.objeto))

    def apagar(self):
        self.btn_apagar.setDisabled(True)
        self.btn_encender.setDisabled(False)
        self.prologRepository.cerrar_objeto(self.objeto)
        self.lbl_estado.setText(self.prologRepository.obtener_estado_objeto(self.objeto))

    def iniciar(self):
        if self.prologRepository.obtener_estado_objeto(self.objeto) == "cerrado":
            self.btn_apagar.setDisabled(True)
            self.btn_encender.setDisabled(False)
            # self.lbl_estado.setText(self.prologRepository.obtener_estado_objeto(self.objeto))
        else:
            self.btn_apagar.setDisabled(False)
            self.btn_encender.setDisabled(True)
            # self.lbl_estado.setText(self.prologRepository.obtener_estado_objeto(self.objeto))

    def llenar_datos(self):
        self.lbl_nombre.setText(self.objeto.nombre)
        self.lbl_estado.setText(self.prologRepository.obtener_estado_objeto(self.objeto))
        self.lbl_tipo.setText(self.objeto.naturaleza)
        set_img_to_label(self.img_objeto, determinar_icono_objeto(self.objeto))

    def retranslateUi(self, dialogo_objeto):
        _translate = QtCore.QCoreApplication.translate
        dialogo_objeto.setWindowTitle(_translate("dialogo_objeto", "Detalle Objeto"))
        self.label.setText(_translate("dialogo_objeto", "Nombre:"))
        self.label_2.setText(_translate("dialogo_objeto", "Tipo:"))
        self.btn_encender.setText(_translate("dialogo_objeto", "Abrir"))
        self.btn_apagar.setText(_translate("dialogo_objeto", "Cerrar"))
        self.label_6.setText(_translate("dialogo_objeto", "Estado:"))
        self.lbl_nombre.setText(_translate("dialogo_objeto", "Valor Nombre"))
        self.lbl_tipo.setText(_translate("dialogo_objeto", "Tipo Nombre"))
        self.lbl_estado.setText(_translate("dialogo_objeto", "Valor Estado"))