# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer_ventana_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from src.modelo.Lugar import Lugar
from src.modelo.Objetos import Objeto
from src.modelo.Planta import Planta


class Ui_ventanaPrincipalDesigner(object):
    def setupUi(self, ventanaPrincipalDesigner):
        ventanaPrincipalDesigner.setObjectName("ventanaPrincipalDesigner")
        ventanaPrincipalDesigner.resize(1120, 876)
        self.centralwidget = QtWidgets.QWidget(ventanaPrincipalDesigner)
        self.centralwidget.setObjectName("centralwidget")
        self.labelTituloVentana = QtWidgets.QLabel(self.centralwidget)
        self.labelTituloVentana.setGeometry(QtCore.QRect(370, 20, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTituloVentana.setFont(font)
        self.labelTituloVentana.setObjectName("labelTituloVentana")
        self.labelNombreCasa_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelNombreCasa_2.setGeometry(QtCore.QRect(10, 100, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelNombreCasa_2.setFont(font)
        self.labelNombreCasa_2.setObjectName("labelNombreCasa_2")
        self.inputNombreCasa = QtWidgets.QLineEdit(self.centralwidget)
        self.inputNombreCasa.setGeometry(QtCore.QRect(150, 100, 211, 21))
        self.inputNombreCasa.setObjectName("inputNombreCasa")
        self.labelPlanta = QtWidgets.QLabel(self.centralwidget)
        self.labelPlanta.setGeometry(QtCore.QRect(10, 230, 261, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelPlanta.setFont(font)
        self.labelPlanta.setObjectName("labelPlanta")
        self.btnAgregarPlanta = QtWidgets.QPushButton(self.centralwidget)
        self.btnAgregarPlanta.setGeometry(QtCore.QRect(10, 260, 75, 23))
        self.btnAgregarPlanta.setObjectName("btnAgregarPlanta")
        self.btnRemoverPlanta = QtWidgets.QPushButton(self.centralwidget)
        self.btnRemoverPlanta.setGeometry(QtCore.QRect(90, 260, 71, 23))
        self.btnRemoverPlanta.setObjectName("btnRemoverPlanta")
        self.lwPlantas = QtWidgets.QListWidget(self.centralwidget)
        self.lwPlantas.setGeometry(QtCore.QRect(10, 290, 301, 192))
        self.lwPlantas.setObjectName("lwPlantas")
        self.labelLugares = QtWidgets.QLabel(self.centralwidget)
        self.labelLugares.setGeometry(QtCore.QRect(370, 225, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelLugares.setFont(font)
        self.labelLugares.setObjectName("labelLugares")
        self.btnAgregarLugar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAgregarLugar.setGeometry(QtCore.QRect(520, 260, 75, 23))
        self.btnAgregarLugar.setObjectName("btnAgregarLugar")
        self.lwLugares = QtWidgets.QListWidget(self.centralwidget)
        self.lwLugares.setGeometry(QtCore.QRect(370, 290, 301, 192))
        self.lwLugares.setObjectName("lwLugares")
        self.btnRemoverLugar = QtWidgets.QPushButton(self.centralwidget)
        self.btnRemoverLugar.setGeometry(QtCore.QRect(600, 260, 71, 23))
        self.btnRemoverLugar.setObjectName("btnRemoverLugar")
        self.btnAgregarObjeto = QtWidgets.QPushButton(self.centralwidget)
        self.btnAgregarObjeto.setGeometry(QtCore.QRect(1030, 260, 71, 23))
        self.btnAgregarObjeto.setObjectName("btnAgregarObjeto")
        self.lwObjetos = QtWidgets.QListWidget(self.centralwidget)
        self.lwObjetos.setGeometry(QtCore.QRect(720, 290, 301, 191))
        self.lwObjetos.setObjectName("lwObjetos")
        self.btnRemoverObjeto = QtWidgets.QPushButton(self.centralwidget)
        self.btnRemoverObjeto.setGeometry(QtCore.QRect(1030, 290, 71, 23))
        self.btnRemoverObjeto.setObjectName("btnRemoverObjeto")
        self.labelObjetos = QtWidgets.QLabel(self.centralwidget)
        self.labelObjetos.setGeometry(QtCore.QRect(720, 225, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelObjetos.setFont(font)
        self.labelObjetos.setObjectName("labelObjetos")
        self.labelCustomizacionHogar = QtWidgets.QLabel(self.centralwidget)
        self.labelCustomizacionHogar.setGeometry(QtCore.QRect(10, 180, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelCustomizacionHogar.setFont(font)
        self.labelCustomizacionHogar.setObjectName("labelCustomizacionHogar")
        self.labelGeneral = QtWidgets.QLabel(self.centralwidget)
        self.labelGeneral.setGeometry(QtCore.QRect(10, 60, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelGeneral.setFont(font)
        self.labelGeneral.setObjectName("labelGeneral")
        self.labelFamilia = QtWidgets.QLabel(self.centralwidget)
        self.labelFamilia.setGeometry(QtCore.QRect(10, 510, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelFamilia.setFont(font)
        self.labelFamilia.setObjectName("labelFamilia")
        self.btnAgregarFamiliar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAgregarFamiliar.setGeometry(QtCore.QRect(160, 550, 75, 23))
        self.btnAgregarFamiliar.setObjectName("btnAgregarFamiliar")
        self.lwFamiliares = QtWidgets.QListWidget(self.centralwidget)
        self.lwFamiliares.setGeometry(QtCore.QRect(10, 580, 301, 192))
        self.lwFamiliares.setObjectName("lwFamiliares")
        self.btnRemoverFamiliar = QtWidgets.QPushButton(self.centralwidget)
        self.btnRemoverFamiliar.setGeometry(QtCore.QRect(240, 550, 71, 23))
        self.btnRemoverFamiliar.setObjectName("btnRemoverFamiliar")
        self.btnFinalizar = QtWidgets.QPushButton(self.centralwidget)
        self.btnFinalizar.setGeometry(QtCore.QRect(920, 790, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnFinalizar.setFont(font)
        self.btnFinalizar.setObjectName("btnFinalizar")
        self.inputFamiliar = QtWidgets.QLineEdit(self.centralwidget)
        self.inputFamiliar.setGeometry(QtCore.QRect(10, 550, 141, 20))
        self.inputFamiliar.setObjectName("inputFamiliar")
        self.labelUbicacion = QtWidgets.QLabel(self.centralwidget)
        self.labelUbicacion.setGeometry(QtCore.QRect(10, 130, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelUbicacion.setFont(font)
        self.labelUbicacion.setObjectName("labelUbicacion")
        self.inputUbicacion = QtWidgets.QLineEdit(self.centralwidget)
        self.inputUbicacion.setGeometry(QtCore.QRect(150, 130, 211, 21))
        self.inputUbicacion.setObjectName("inputUbicacion")
        self.inputLugar = QtWidgets.QLineEdit(self.centralwidget)
        self.inputLugar.setGeometry(QtCore.QRect(370, 260, 141, 21))
        self.inputLugar.setObjectName("inputLugar")
        self.inputObjeto = QtWidgets.QLineEdit(self.centralwidget)
        self.inputObjeto.setGeometry(QtCore.QRect(720, 260, 111, 21))
        self.inputObjeto.setObjectName("inputObjeto")
        self.cbxTipo = QtWidgets.QComboBox(self.centralwidget)
        self.cbxTipo.setGeometry(QtCore.QRect(840, 260, 101, 22))
        self.cbxTipo.setObjectName("cbxTipo")
        self.cbxTipo.addItem("")
        self.cbxTipo.addItem("")
        self.cbxTipo.addItem("")
        self.cbxTipo.addItem("")
        self.inputUnidad = QtWidgets.QLineEdit(self.centralwidget)
        self.inputUnidad.setGeometry(QtCore.QRect(950, 260, 71, 21))
        self.inputUnidad.setObjectName("inputUnidad")
        ventanaPrincipalDesigner.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ventanaPrincipalDesigner)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 21))
        self.menubar.setObjectName("menubar")
        ventanaPrincipalDesigner.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ventanaPrincipalDesigner)
        self.statusbar.setObjectName("statusbar")
        ventanaPrincipalDesigner.setStatusBar(self.statusbar)

        self.retranslateUi(ventanaPrincipalDesigner)
        QtCore.QMetaObject.connectSlotsByName(ventanaPrincipalDesigner)
        self.btnAgregarPlanta.clicked.connect(self.SetPlantas)
        self.btnRemoverPlanta.clicked.connect(self.RemovePlantas)
        self.btnAgregarLugar.clicked.connect(self.SetLugares)
        self.btnRemoverLugar.clicked.connect(self.RemoveLugares)
        self.btnAgregarObjeto.clicked.connect(self.SetObjetos)
        self.btnRemoverObjeto.clicked.connect(self.RemoveObjeto)
        self.btnAgregarFamiliar.clicked.connect(self.SetFamilias)
        self.btnRemoverFamiliar.clicked.connect(self.RemoveFamiliares)

    contadorplanta = 1
    contadorLugar = 1
    contadorObjeto = 1
    plantas = []
    lugares = []


    def retranslateUi(self, ventanaPrincipalDesigner):
        _translate = QtCore.QCoreApplication.translate
        ventanaPrincipalDesigner.setWindowTitle(_translate("ventanaPrincipalDesigner", "Home Designer"))
        self.labelTituloVentana.setText(_translate("ventanaPrincipalDesigner", "Configuración  Inicial de su Casa"))
        self.labelNombreCasa_2.setText(_translate("ventanaPrincipalDesigner", "Nombre de su casa:"))
        self.labelPlanta.setText(_translate("ventanaPrincipalDesigner", "Plantas"))
        self.btnAgregarPlanta.setText(_translate("ventanaPrincipalDesigner", "Agregar"))
        self.btnRemoverPlanta.setText(_translate("ventanaPrincipalDesigner", "Remover"))
        self.labelLugares.setText(_translate("ventanaPrincipalDesigner", "Lugares"))
        self.btnAgregarLugar.setText(_translate("ventanaPrincipalDesigner", "Agregar"))
        self.btnRemoverLugar.setText(_translate("ventanaPrincipalDesigner", "Remover"))
        self.btnAgregarObjeto.setText(_translate("ventanaPrincipalDesigner", "Agregar"))
        self.btnRemoverObjeto.setText(_translate("ventanaPrincipalDesigner", "Remover"))
        self.labelObjetos.setText(_translate("ventanaPrincipalDesigner", "Objetos"))
        self.labelCustomizacionHogar.setText(_translate("ventanaPrincipalDesigner", "Customización del Hogar"))
        self.labelGeneral.setText(_translate("ventanaPrincipalDesigner", "General"))
        self.labelFamilia.setText(_translate("ventanaPrincipalDesigner", "Familia"))
        self.btnAgregarFamiliar.setText(_translate("ventanaPrincipalDesigner", "Agregar"))
        self.btnRemoverFamiliar.setText(_translate("ventanaPrincipalDesigner", "Remover"))
        self.btnFinalizar.setText(_translate("ventanaPrincipalDesigner", "Finalizar"))
        self.inputFamiliar.setPlaceholderText(_translate("ventanaPrincipalDesigner", "Ingresar nombre del familiar"))
        self.labelUbicacion.setText(_translate("ventanaPrincipalDesigner", "Ubicación:"))
        self.cbxTipo.setItemText(0, _translate("ventanaPrincipalDesigner", "<Tipo Objeto>"))
        self.cbxTipo.setItemText(1, _translate("ventanaPrincipalDesigner", "Electrodomestico"))
        self.cbxTipo.setItemText(2, _translate("ventanaPrincipalDesigner", "Agua"))
        self.cbxTipo.setItemText(3, _translate("ventanaPrincipalDesigner", "Contundente"))
        self.inputUnidad.setPlaceholderText(_translate("ventanaPrincipalDesigner", "consumo"))

    def SetPlantas(self):
        planta = Planta("Planta"+str(self.contadorplanta))
        self.lwPlantas.addItem("Planta"+str(self.contadorplanta))
        self.plantas.append(planta)
        self.contadorplanta += 1

    def RemovePlantas(self):
        listItems = self.lwPlantas.selectedItems()
        if not listItems: return
        for item in listItems:
            self.lwPlantas.takeItem(self.lwPlantas.row(item))
            itemplanta = item.text()
            for aux in self.plantas:
                if aux.nombre == item.text():
                    self.plantas.remove(aux)

        self.contadorplanta = self.contadorplanta-1

    def SetLugares(self):
        lugar = Lugar(self.inputLugar.text()+str(self.contadorLugar))
        self.lwLugares.addItem(self.inputLugar.text()+str(self.contadorLugar))
        self.lugares.append(lugar)
        listItems = self.lwPlantas.selectedItems()
        if not listItems: return
        for item in listItems:
            itemplanta = item.text()
            for aux in self.plantas:
                if aux.nombre == item.text():
                    aux.lugares.append(lugar)
        self.contadorLugar += 1

    def RemoveLugares(self):
        listItems = self.lwLugares.selectedItems()
        listItemsPlanta = self.lwPlantas.selectedItems()
        if not listItems: return
        for itemp in listItemsPlanta:
            itemplanta = itemp.text()
        for item in listItems:
            self.lwLugares.takeItem(self.lwLugares.row(item))
            itemlugar = item.text()
            for aux in self.plantas:
                if aux.nombre == itemplanta:
                    for aux1 in aux.lugares:
                        if aux1.nombre == itemlugar:
                            aux.lugares.remove(aux1)

        self.contadorLugar = self.contadorLugar - 1

    def GetAllPlantas(self, plantaselected, lugarselected):

        for aux in self.plantas:
            if aux.nombre == plantaselected:
                for aux1 in aux.lugares:
                    if aux1.nombre == lugarselected:
                        return aux1



    def SetObjetos(self):
        objeto = Objeto(self.inputObjeto.text()+str(self.contadorObjeto),self.cbxTipo.currentText(),self.inputUnidad.text())
        self.lwObjetos.addItem(self.inputObjeto.text()+str(self.contadorObjeto))
        listItemsPlanta = self.lwPlantas.selectedItems()
        listItems = self.lwLugares.selectedItems()
        if not listItemsPlanta: return
        for itemp in listItemsPlanta:
            itemplanta = itemp.text()
            for item in listItems:
                self.lwLugares.row(item)
                itemlugar = item.text()
                lugars = self.GetAllPlantas(itemplanta,itemlugar)
                lugars.objetos.append(objeto)



        self.contadorObjeto += 1

    def RemoveObjeto(self):
        listItems = self.lwObjetos.selectedItems()
        if not listItems: return
        for item in listItems:
            self.lwObjetos.takeItem(self.lwObjetos.row(item))
        self.contadorObjeto = self.contadorObjeto - 1

    def SetFamilias(self):
        self.lwFamiliares.addItem(self.inputFamiliar.text())

    def RemoveFamiliares(self):
        listItems = self.lwFamiliares.selectedItems()
        if not listItems: return
        for item in listItems:
            self.lwFamiliares.takeItem(self.lwFamiliares.row(item))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventanaPrincipalDesigner = QtWidgets.QMainWindow()
    ui = Ui_ventanaPrincipalDesigner()
    ui.setupUi(ventanaPrincipalDesigner)
    ventanaPrincipalDesigner.show()
    sys.exit(app.exec_())
